[tasks.up]
command = "docker"
args = ["compose", "-f", "infra/docker-compose.yml", "up", "-d"]

[tasks.down]
command = "docker"
args = ["compose", "-f", "infra/docker-compose.yml", "down"]


[tasks.front-install]
cwd = "web"
command = "bun"
args = ["install"]

[tasks.front-dev]
cwd = "web"
command = "bun"
args = ["run", "dev"]
dependencies = ["front-install"]

[tasks.front-build]
cwd = "web"
command = "bun"
args = ["run", "build"]
dependencies = ["front-install"]


[tasks.analyzer-run]
cwd = "analyzer"
command = "cargo"
args = ["run"]

[tasks.analyzer-build]
command = "docker"
args = ["build", "-f", "infra/analyzer/Dockerfile", "-t", "igo-nikki-analyzer", "."]


[tasks.hasura_metadata-update]
cwd = "infra/hasura"
script = '''
rm -rf metadata
hasura --skip-update-check metadata export --admin-secret hasura
'''

[tasks.graphql_schema-update]
cwd = "graphql"
script = '''
npx graphqurl http://localhost:20180/v1/graphql -H "X-Hasura-Admin-Secret: hasura" --introspect > schema.graphql
'''
